"""Configuration Settings"""

SESSION_TIMEOUT = 900
MAX_LOGIN_ATTEMPTS = 5
ACCOUNT_LOCK_DURATION = 900
MIN_PASSWORD_LENGTH = 6
ATTENDANCE_EDIT_WINDOW = 24
DEFAULT_ATTENDANCE_THRESHOLD = 75
WARNING_THRESHOLD = 65
CRITICAL_THRESHOLD = 50
MAX_AUDIT_LOGS = 100
ATTENDANCE_STATUS = ["present", "absent", "late", "excused"]
USER_ROLES = ["admin", "faculty", "student"]
